name: CI/CD for Frontend

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: Ubuntu-Latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: Log in to Azure
              uses: azure/login@v1
              with:
                creds: $'{{ secret.AZURE_SECRET }}'

            - name: Deploy to Azure Storage
              run: |
                az storage blob upload-batch \
                --acount-name "crcresumestorage" \
                --destination "$web" \
                --source "."

            # - name: Purge Azure CDN endpoint
            #   run: |
            #     az cdn endpoint purge \
            #     --resource-group " \
            #     --profile-name "" \
            #     --name "" \
            #     --content-paths '/*'