name: CI/CD for Frontend

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: Ubuntu-Latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Replace API endpoint in script.js
              run: sed -i "s|%%AZURE_FUNCTION_URL%%|${{ secrets.AZURE_FUNCTION_URL }}|g" counter.js

            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: '${{ secrets.AZURE_SECRET }}'

            - name: Sync files to Azure Blob Storage
              uses: 'azure/CLI@v1'
              with:
                azcliversion: '2.40.0'
                inlineScript: |
                  az storage blob upload-batch \
                    --account-name crcresumestorage \
                    --source . \
                    --destination '$web' \
                    --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
                    --overwrite
              env:
                AZURE_STORAGE_CONNECTION_STRING: $${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

            - name: Purge Azure CDN endpoint
              run: |
                az afd endpoint purge \
                --resource-group crc-rg \
                --profile-name crc-hosting \
                --endpoint-name asim-crc-resume-f6dveqa5ffbsbshn \
                --domains asim-crc-resume.cloud \
                --content-paths '/*'